### ISSUE TITLE
Analysis plan feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#10]
**Analysis plan shows significant thought has been put into this project, but some clarifications are necessary**

Point of confusion: Your research question asks “Do judges consider other factors such as the fighters win streak or size?” Then in step 2 you talk about how only “features that are indictive of current fight performance” will be used and others will be dropped. How will you investigate whether judges consider other factors if these are dropped? Pick your approach and clarify your proposal. (My impulse is to stick with only looking at indicitive features and adjusting the reserch question but we can discuss this.)

Good observation about how weights are important to your research question and how that impacts possible models to use.

> “Potential models that may be used include”

Recommend picking and sticking with one model unless there's a compelling reason to consider multiple – in which case, explain how you will pick between the models as your analysis progresses.

**Comment by ksedivyhaley** [comment]
Additional notes:

- Clarify which features in the data set are considered "indictive of current fight performance" (ie, which variables are you ultimately including in the analysis and what do they mean?)
- What model metric will you use for hyperparameter optimization?
- How will you validate your model?

You want to have a step by step outline of what you're going to do. See [Tiffany's example](https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1) (introduction paragraphs 3 and after) for the level of detail.

**Comment by SamEdwardes** [comment]
Thank you for the feedback. Agreed the analysis could be more concise and on your points of confusion. We will look to update these in the proposal document for lab 2.
