### ISSUE TITLE
Download script failure - testing

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#12]
Download script halts execution with message "URL doesn't exist", but works if your test using url.exists is removed. The test is a good idea but it looks like there's a [possibility for false negatives on URLs](https://stackoverflow.com/questions/52911812/check-if-url-exists-in-r).

**Comment by SamEdwardes** [comment]
Thank you for the catch. It looks to be an `RCurl`. The testing did work on our computer, so maybe a version of `RCurl` issue? Either way agreed this can be removed.

**Comment by ksedivyhaley** [comment]
Based on my quick search for similar errors it looks like it might be something to do with the internet configuration.

I'm also noting you haven't listed dependencies - what version of RCurl are you using? I'm running RCurl_1.95-4.12.

It is important to have tests, so this should either be fixed or replaced with a better test.

**Comment by SamEdwardes** [comment]
Thanks for the follow up. We will list dependencies in a future release. I think the best course of action on this item is to just remove the url.exists() check and just let the script fail on its own if no valid URL is give.

**Comment by SamEdwardes** [comment]
@scao1 and @sweber15  I have updated the download script and will include in the next PR.

**Comment by SamEdwardes** [comment]
Corrected in #14
