### ISSUE TITLE
Minor feedback (Not priority to implement)

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#13]
**Good stuff!**

- Submission links good for all group members
- Files good: Teamwork contract, license, contributing, Code (but see below)
- Issues and commits look good
- Download script is well documented - useage example with the URL used is helpful.

**Room for improvement**

- Repo organization ok, but: 
  - where will data live?
  - recommend getting rid of blank files once you have actual files in those folders
- Code of conduct issue: you say reporting is confidential, but tell people to report using issues, which are not confidential.
- Proposal should discuss EDA
- Inclusion of background is helpful, but consider whether it is possible to be more concise
- Over-use of point form

**Comment by SamEdwardes** [comment]
thank you for the feedback, closing this issue as it is low priority.
