### ISSUE TITLE
Problems with writing plots.

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI522_group315#17]
Note that you may encounter issues with scripts 3 and 4 which write plots to the analysis directory. If errors are encountered please check:

- Chrome of Firefox is installed on your machine
- `conda install selenium` (or `pip install selenium`) (check for updates as well)
- `brew cask install chromedriver` (or `brew cask upgrade chromedriver`)

**Comment by sweber15** [comment]
Thank you for bring this up Sam. I will add it to the dependencies list. 

I'd also like to add that this worked for downloading the driver for me:

`conda install selenium`

I also had to set my path variable manually to the folder where the ChromeDriver was downloaded. Additionally you can try to use: 

`conda install -c conda-forge python-chromedriver-binary`

**Comment by scao1** [comment]
I will update the readme and add to the dependencies list. And another package you need to install for running script3 is GGally. I'll add that too.

**Comment by sweber15** [comment]
Subing, I'm updating the readme right now with my python dependencies. I'll send a PR with mine in about 10 minutes.

**Comment by scao1** [comment]
I need to change the readme according to the structure the TA has pointed us to (The breast cancer analysis). You can post your dependency here and I'll add it.

**Comment by sweber15** [comment]
Hi Subing, I was just writing it up!

Python dependencies:

Python 3.7.3 and Python packages:
- docopt==0.6.2
- requests==2.22.0
- pandas==0.24.2
- scikit-learn==0.22.1
- numpy==1.16.4
- altair==3.2.0
- selenium==3.141.0
- matplotlib==3.1.0

ChromeDriver 79.0.3945.36 - [Download](https://chromedriver.chromium.org/)
- Note: Users may have an issue producing altair plots. You may need to download the latest version of ChomeDriver. For further information see [Issue #17](https://github.com/UBC-MDS/DSCI522_group315/issues/17).

**Comment by scao1** [comment]
Great. Thanks!

**Comment by SamEdwardes** [comment]
Thanks team, sounds like it’s coming together. FYI I copied the old read me into proposal MD. So you can delete everything in the current version to match the format Tiffany has shown is.

**Comment by ksedivyhaley** [comment]
> Note that you may encounter issues with scripts 3 and 4 which write plots to the analysis directory. If errors are encountered please check:
> 
> * Chrome of Firefox is installed on your machine
> * `conda install selenium` (or `pip install selenium`) (check for updates as well)
> * `brew cask install chromedriver` (or `brew cask upgrade chromedriver`)

brew cask appears to be a mac command. 

> I also had to set my path variable manually to the folder where the ChromeDriver was downloaded. 

Explain how to do this. 

If this is a likely usage problem then you need clearer instructions for dealing with it.
