### ISSUE TITLE
To List - Week #1

### ISSUE THREAD

**Issue by sweber15** [UBC-MDS/DSCI522_group315#2]
- [x] 1. Team work contract - Sarah share on slack and discuss at Friday meeting. 
- [x] 2.  Code of Conduct - Sam
- [x] 3. Contributing File - Sarah
- [x] 4. License - complete
- [x] 5. Project proposal - Sam
    - [x] Project data set - complete
    - [x] Research Question
    - [x] Create a plan
- [x] 6. Script data - Subing
- [x] 7. EDA - Sarah and Subing
    - [x] Plots to explore questions 
    - [x] Set up EDA document - Sarah
    - [x] See book chapter 4: Art of Data Science

Other: 

- [x]  File Directory - Sarah
- [x]  README description - Sam

Roles: 
1. Leader: Sam
2. Scribe: Sarah
3. Proof Reader: Subing

**Comment by SamEdwardes** [comment]
Hey team, I have completed the project proposal (#4). Can you please review?

**Comment by SamEdwardes** [comment]
@scao1 - just a reminder that when creating our final submission we need to create a version:

> Create a release on your project repo named v1.0 and submit that URL in your milestone1 repo's README.md file so we know where to find it.

Can you please let us know on Slack after you have reviewed and created the release so that we can update our README files?

**Comment by sweber15** [comment]
I started the EDA document. I had to merge two of the csv files from the original data source to be able to filter by decision. If there is anything you want to explore, please feel free to play around with the data. I highly recommend playing around with different charts if you have any ideas of what we can analysis visually or if there is a simple solution we can explore.
