### ISSUE TITLE
Script feedback: need tests!

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#24]
- Download needs test, see previous issue #12 (quote below)
- Preprocess and EDA also need tests
- Documentation is very good!
  - Make sure to update usage description for download to include the 01_ script tag.
- In Analysis, simplify paths - I recommend hard coding your train/test split file names and then just giving the path to those files as one input parameter.

> It is important to have tests, so this should either be fixed or replaced with a better test.

_Originally posted by @ksedivyhaley in https://github.com/UBC-MDS/DSCI522_group315/issues/12#issuecomment-577532133_

**Comment by SamEdwardes** [comment]
Tests have been added for scripts 1 to 4.
