### ISSUE TITLE
Report feedback

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#27]
- Good introduction of question
- Data introduction pretty good, but list the features related to fight performance.
- Results interpretation generally good, to improve:
  - Validation error looks lower at 5 features - explain why 8-11 was better overall.
  - Text duplicated: "The criteria sets priority from high to low ranking **effective Striking/Grappling, effective Striking/Grappling** and cage/ring Control(The ABC MMA Rules Committee 2017)."
  - Elaborate a bit more on the predictors that are heavily weighted that aren't Striking/Grappling performance.
- Be more specific/detailed in your critique of the analysis and how you would improve and optimize the model.

**Comment by SamEdwardes** [comment]
Corrections have been made under v3.0
