### ISSUE TITLE
Visualizations - some formatting improvements

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#28]
- Use clearer labels for features rather than head_att. You don't want the reader to have to constantly cross-reference these.
  - figure labels should have appropriate capitalization and no underscores
- Figure 1 should have larger text and nicer labels.
- Figure 2 is well chosen overall but should have clearer labels (size, and use Winner=Red/Blue rather than Blue Winner=0/1. Colour key should be categorical rather than a gradient (perhaps colour red for red wins, blue for blue wins?)
- Table 2 is almost perfect - just list fewer significant digits!
- Confusion matrix is excellent. All figures should be formatted like this!

**Comment by SamEdwardes** [comment]
Most feedback has been implemented under v3.0
