### ISSUE TITLE
Need to better document ChromeDriver issues

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#29]
> Note that you may encounter issues with scripts 3 and 4 which write plots to the analysis directory. If errors are encountered please check:
> 
> * Chrome of Firefox is installed on your machine
> * `conda install selenium` (or `pip install selenium`) (check for updates as well)
> * `brew cask install chromedriver` (or `brew cask upgrade chromedriver`)

brew cask appears to be a mac command. 

> I also had to set my path variable manually to the folder where the ChromeDriver was downloaded. 

Explain how to do this. 

If this is a likely usage problem then you need clearer instructions for dealing with it.

_Originally posted by @ksedivyhaley in https://github.com/UBC-MDS/DSCI522_group315/issues/17#issuecomment-579971728_

**Comment by SamEdwardes** [comment]
Thanks for the feedback Kate. I wonder if this useful to really document though? Next week we will be "dockerizing" everything which will probably open up a new host of issues. I would rather spend time clearly documenting any issues that come up with that.

What are your thoughts?

**Comment by ksedivyhaley** [comment]
For the purposes of the next Milestones, you can focus on the other improvements and on making sure that the dockerizing works well and is properly documented.

However, to give you an idea of how important this sort of documentation is for future work, I have still not been able to run these scripts because I was not able to fix the issue with ChromeDriver within the time allotted to mark your assignment. 

It's great that you were aware of the possible issue and that you warned the user ahead of time - but without good instructions for fixing the problem, they're likely to hit a wall and be unable to reproduce your analysis! Linking to an issue is better than nothing, but because issues are used for back and forth communication, they aren't always structured in a way that makes it easy to figure out the steps required to fix the problem.

**Comment by SamEdwardes** [comment]
OK thank you for the response Kate!

**Comment by SamEdwardes** [comment]
Most feedback has been implemented under v3.0
