### ISSUE TITLE
Feedback from Evhen and James

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI522_group315#34]
Code:

- try and create more functions to modularize code. e.g. instead of having headers, it would make sense to have functions

Model choice:

- try more models (e.g. adabost), do we get the same results?
- does it make sense to have RFE? The judges see and should consider all of these factors.

Bash script:

- put some echo lines in there to let the user know what they are doing.

Report:

- make figs more readable

**Comment by sweber15** [comment]
Thank you for the feedback. Feedback is compiled in issue #35
